[project]
name = "parallelization-tutorial-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.2",
    "numpy>=2.2.6",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
]
